"use strict";

const {
  Annotation,
  AnnotationType,
  ChangeDesc,
  ChangeSet,
  CharCategory,
  Compartment,
  EditorSelection,
  EditorState,
  Facet,
  Line,
  MapMode,
  Prec,
  Range,
  RangeSet,
  RangeSetBuilder,
  RangeValue,
  SelectionRange,
  StateEffect,
  StateEffectType,
  StateField,
  Text,
  Transaction,
  codePointAt,
  codePointSize,
  combineConfig,
  countColumn,
  findClusterBreak,
  findColumn,
  fromCodePoint,
} = require("@codemirror/state");
const {
  BidiSpan,
  BlockInfo,
  BlockType,
  BlockWrapper,
  Decoration,
  Direction,
  EditorView,
  GutterMarker,
  MatchDecorator,
  RectangleMarker,
  ViewPlugin,
  ViewUpdate,
  WidgetType,
  __test,
  closeHoverTooltips,
  crosshairCursor,
  drawSelection,
  dropCursor,
  getDialog,
  getDrawSelectionConfig,
  getPanel,
  getTooltip,
  gutter,
  gutterLineClass,
  gutterWidgetClass,
  gutters,
  hasHoverTooltips,
  highlightActiveLine,
  highlightActiveLineGutter,
  highlightSpecialChars,
  highlightTrailingWhitespace,
  highlightWhitespace,
  hoverTooltip,
  keymap,
  layer,
  lineNumberMarkers,
  lineNumberWidgetMarker,
  lineNumbers,
  logException,
  panels,
  placeholder,
  rectangularSelection,
  repositionTooltips,
  runScopeHandlers,
  scrollPastEnd,
  showDialog,
  showPanel,
  showTooltip,
  tooltips,
} = require("@codemirror/view");
const {
  DefaultBufferLength,
  IterMode,
  MountedTree,
  NodeProp,
  NodeSet,
  NodeType,
  NodeWeakMap,
  Parser,
  Tree,
  TreeBuffer,
  TreeCursor,
  TreeFragment,
  parseMixed,
} = require("@lezer/common");
const {
  Tag: Tag0,
  classHighlighter,
  getStyleTags,
  highlightCode,
  highlightTree,
  styleTags,
  tagHighlighter,
  tags,
} = require("@lezer/highlight");
const {
  DocInput,
  HighlightStyle,
  IndentContext,
  LRLanguage,
  Language,
  LanguageDescription,
  LanguageSupport,
  ParseContext,
  StreamLanguage,
  StringStream,
  TreeIndentContext,
  bidiIsolates,
  bracketMatching,
  bracketMatchingHandle,
  codeFolding,
  continuedIndent,
  defaultHighlightStyle,
  defineLanguageFacet,
  delimitedIndent,
  ensureSyntaxTree,
  flatIndent,
  foldAll,
  foldCode,
  foldEffect,
  foldGutter,
  foldInside,
  foldKeymap,
  foldNodeProp,
  foldService,
  foldState,
  foldable,
  foldedRanges,
  forceParsing,
  getIndentUnit,
  getIndentation,
  highlightingFor,
  ignoreSpellcheckToken,
  indentNodeProp,
  indentOnInput,
  indentRange,
  indentService,
  indentString,
  indentUnit,
  language,
  languageDataProp,
  lineClassNodeProp,
  lineHighlighter,
  matchBrackets,
  sublanguageProp,
  syntaxHighlighting,
  syntaxParserRunning,
  syntaxTree,
  syntaxTreeAvailable,
  toggleFold,
  tokenClassNodeProp,
  unfoldAll,
  unfoldCode,
  unfoldEffect,
} = require("@codemirror/language");
const {
  blockComment,
  blockUncomment,
  copyLineDown,
  copyLineUp,
  cursorCharBackward,
  cursorCharBackwardLogical,
  cursorCharForward,
  cursorCharForwardLogical,
  cursorCharLeft,
  cursorCharRight,
  cursorDocEnd,
  cursorDocStart,
  cursorGroupBackward,
  cursorGroupForward,
  cursorGroupForwardWin,
  cursorGroupLeft,
  cursorGroupRight,
  cursorLineBoundaryBackward,
  cursorLineBoundaryForward,
  cursorLineBoundaryLeft,
  cursorLineBoundaryRight,
  cursorLineDown,
  cursorLineEnd,
  cursorLineStart,
  cursorLineUp,
  cursorMatchingBracket,
  cursorPageDown,
  cursorPageUp,
  cursorSubwordBackward,
  cursorSubwordForward,
  cursorSyntaxLeft,
  cursorSyntaxRight,
  defaultKeymap,
  deleteCharBackward,
  deleteCharBackwardStrict,
  deleteCharForward,
  deleteGroupBackward,
  deleteGroupForward,
  deleteLine,
  deleteLineBoundaryBackward,
  deleteLineBoundaryForward,
  deleteToLineEnd,
  deleteToLineStart,
  deleteTrailingWhitespace,
  emacsStyleKeymap,
  history,
  historyField,
  historyKeymap,
  indentLess,
  indentMore,
  indentSelection,
  indentWithTab,
  insertBlankLine,
  insertNewline,
  insertNewlineAndIndent,
  insertNewlineKeepIndent,
  insertTab,
  invertedEffects,
  isolateHistory,
  lineComment,
  lineUncomment,
  moveLineDown,
  moveLineUp,
  redo,
  redoDepth,
  redoSelection,
  selectAll,
  selectCharBackward,
  selectCharBackwardLogical,
  selectCharForward,
  selectCharForwardLogical,
  selectCharLeft,
  selectCharRight,
  selectDocEnd,
  selectDocStart,
  selectGroupBackward,
  selectGroupForward,
  selectGroupForwardWin,
  selectGroupLeft,
  selectGroupRight,
  selectLine,
  selectLineBoundaryBackward,
  selectLineBoundaryForward,
  selectLineBoundaryLeft,
  selectLineBoundaryRight,
  selectLineDown,
  selectLineEnd,
  selectLineStart,
  selectLineUp,
  selectMatchingBracket,
  selectPageDown,
  selectPageUp,
  selectParentSyntax,
  selectSubwordBackward,
  selectSubwordForward,
  selectSyntaxLeft,
  selectSyntaxRight,
  simplifySelection,
  splitLine,
  standardKeymap,
  temporarilySetTabFocusMode,
  toggleBlockComment,
  toggleBlockCommentByLine,
  toggleComment,
  toggleLineComment,
  toggleTabFocusMode,
  transposeChars,
  undo,
  undoDepth,
  undoSelection,
} = require("@codemirror/commands");
const {
  RegExpCursor,
  SearchCursor,
  SearchQuery,
  closeSearchPanel,
  findNext,
  findPrevious,
  getSearchQuery,
  gotoLine,
  highlightSelectionMatches,
  openSearchPanel,
  replaceAll,
  replaceNext,
  search,
  searchKeymap,
  searchPanelOpen,
  selectMatches,
  selectNextOccurrence,
  selectSelectionMatches,
  setSearchQuery,
} = require("@codemirror/search");
const { ContextTracker, ExternalTokenizer, InputStream, LRParser, LocalTokenGroup, Stack } = require("@lezer/lr");
const {
  CompletionContext,
  acceptCompletion,
  autocompletion,
  clearSnippet,
  closeBrackets,
  closeBracketsKeymap,
  closeCompletion,
  completeAnyWord,
  completeFromList,
  completionKeymap,
  completionStatus,
  currentCompletions,
  deleteBracketPair,
  hasNextSnippetField,
  hasPrevSnippetField,
  ifIn,
  ifNotIn,
  insertBracket,
  insertCompletionText,
  moveCompletionSelection,
  nextSnippetField,
  pickedCompletion,
  prevSnippetField,
  selectedCompletion,
  selectedCompletionIndex,
  setSelectedCompletion,
  snippet,
  snippetCompletion,
  snippetKeymap,
  startCompletion,
} = require("@codemirror/autocomplete");
const {
  collab,
  getClientID,
  getSyncedVersion,
  rebaseUpdates,
  receiveUpdates,
  sendableUpdates,
} = require("@codemirror/collab");
var codemirrorRangeset = {
  Annotation: () => Annotation,
  AnnotationType: () => AnnotationType,
  ChangeDesc: () => ChangeDesc,
  ChangeSet: () => ChangeSet,
  CharCategory: () => CharCategory,
  Compartment: () => Compartment,
  EditorSelection: () => EditorSelection,
  EditorState: () => EditorState,
  Facet: () => Facet,
  Line: () => Line,
  MapMode: () => MapMode,
  Prec: () => Prec,
  Range: () => Range,
  RangeSet: () => RangeSet,
  RangeSetBuilder: () => RangeSetBuilder,
  RangeValue: () => RangeValue,
  SelectionRange: () => SelectionRange,
  StateEffect: () => StateEffect,
  StateEffectType: () => StateEffectType,
  StateField: () => StateField,
  Text: () => Text,
  Transaction: () => Transaction,
  codePointAt: () => codePointAt,
  codePointSize: () => codePointSize,
  combineConfig: () => combineConfig,
  countColumn: () => countColumn,
  findClusterBreak: () => findClusterBreak,
  findColumn: () => findColumn,
  fromCodePoint: () => fromCodePoint,
};
var codemirrorTooltip = {
  BidiSpan: () => BidiSpan,
  BlockInfo: () => BlockInfo,
  BlockType: () => BlockType,
  Decoration: () => Decoration,
  Direction: () => Direction,
  EditorView: () => EditorView,
  GutterMarker: () => GutterMarker,
  MatchDecorator: () => MatchDecorator,
  RectangleMarker: () => RectangleMarker,
  ViewPlugin: () => ViewPlugin,
  ViewUpdate: () => ViewUpdate,
  WidgetType: () => WidgetType,
  __test: () => __test,
  closeHoverTooltips: () => closeHoverTooltips,
  crosshairCursor: () => crosshairCursor,
  drawSelection: () => drawSelection,
  dropCursor: () => dropCursor,
  getDialog: () => getDialog,
  getDrawSelectionConfig: () => getDrawSelectionConfig,
  getPanel: () => getPanel,
  getTooltip: () => getTooltip,
  gutter: () => gutter,
  gutterLineClass: () => gutterLineClass,
  gutterWidgetClass: () => gutterWidgetClass,
  gutters: () => gutters,
  hasHoverTooltips: () => hasHoverTooltips,
  highlightActiveLine: () => highlightActiveLine,
  highlightActiveLineGutter: () => highlightActiveLineGutter,
  highlightSpecialChars: () => highlightSpecialChars,
  highlightTrailingWhitespace: () => highlightTrailingWhitespace,
  highlightWhitespace: () => highlightWhitespace,
  hoverTooltip: () => hoverTooltip,
  keymap: () => keymap,
  layer: () => layer,
  lineNumberMarkers: () => lineNumberMarkers,
  lineNumberWidgetMarker: () => lineNumberWidgetMarker,
  lineNumbers: () => lineNumbers,
  logException: () => logException,
  panels: () => panels,
  placeholder: () => placeholder,
  rectangularSelection: () => rectangularSelection,
  repositionTooltips: () => repositionTooltips,
  runScopeHandlers: () => runScopeHandlers,
  scrollPastEnd: () => scrollPastEnd,
  showDialog: () => showDialog,
  showPanel: () => showPanel,
  showTooltip: () => showTooltip,
  tooltips: () => tooltips,
};
var lezerCommon = {
  DefaultBufferLength: () => DefaultBufferLength,
  IterMode: () => IterMode,
  MountedTree: () => MountedTree,
  NodeProp: () => NodeProp,
  NodeSet: () => NodeSet,
  NodeType: () => NodeType,
  NodeWeakMap: () => NodeWeakMap,
  Parser: () => Parser,
  Tree: () => Tree,
  TreeBuffer: () => TreeBuffer,
  TreeCursor: () => TreeCursor,
  TreeFragment: () => TreeFragment,
  parseMixed: () => parseMixed,
};
var lezerHighlight = {
  Tag: () => Tag0,
  classHighlighter: () => classHighlighter,
  getStyleTags: () => getStyleTags,
  highlightCode: () => highlightCode,
  highlightTree: () => highlightTree,
  styleTags: () => styleTags,
  tagHighlighter: () => tagHighlighter,
  tags: () => tags,
};
var codemirrorStreamParser = {
  DocInput: () => DocInput,
  HighlightStyle: () => HighlightStyle,
  IndentContext: () => IndentContext,
  LRLanguage: () => LRLanguage,
  Language: () => Language,
  LanguageDescription: () => LanguageDescription,
  LanguageSupport: () => LanguageSupport,
  ParseContext: () => ParseContext,
  StreamLanguage: () => StreamLanguage,
  StringStream: () => StringStream,
  TreeIndentContext: () => TreeIndentContext,
  bidiIsolates: () => bidiIsolates,
  bracketMatching: () => bracketMatching,
  bracketMatchingHandle: () => bracketMatchingHandle,
  codeFolding: () => codeFolding,
  continuedIndent: () => continuedIndent,
  defaultHighlightStyle: () => defaultHighlightStyle,
  defineLanguageFacet: () => defineLanguageFacet,
  delimitedIndent: () => delimitedIndent,
  ensureSyntaxTree: () => ensureSyntaxTree,
  flatIndent: () => flatIndent,
  foldAll: () => foldAll,
  foldCode: () => foldCode,
  foldEffect: () => foldEffect,
  foldGutter: () => foldGutter,
  foldInside: () => foldInside,
  foldKeymap: () => foldKeymap,
  foldNodeProp: () => foldNodeProp,
  foldService: () => foldService,
  foldState: () => foldState,
  foldable: () => foldable,
  foldedRanges: () => foldedRanges,
  forceParsing: () => forceParsing,
  getIndentUnit: () => getIndentUnit,
  getIndentation: () => getIndentation,
  highlightingFor: () => highlightingFor,
  ignoreSpellcheckToken: () => ignoreSpellcheckToken,
  indentNodeProp: () => indentNodeProp,
  indentOnInput: () => indentOnInput,
  indentRange: () => indentRange,
  indentService: () => indentService,
  indentString: () => indentString,
  indentUnit: () => indentUnit,
  language: () => language,
  languageDataProp: () => languageDataProp,
  lineClassNodeProp: () => lineClassNodeProp,
  lineHighlighter: () => lineHighlighter,
  matchBrackets: () => matchBrackets,
  sublanguageProp: () => sublanguageProp,
  syntaxHighlighting: () => syntaxHighlighting,
  syntaxParserRunning: () => syntaxParserRunning,
  syntaxTree: () => syntaxTree,
  syntaxTreeAvailable: () => syntaxTreeAvailable,
  toggleFold: () => toggleFold,
  tokenClassNodeProp: () => tokenClassNodeProp,
  unfoldAll: () => unfoldAll,
  unfoldCode: () => unfoldCode,
  unfoldEffect: () => unfoldEffect,
};
var codemirrorHistory = {
  blockComment: () => blockComment,
  blockUncomment: () => blockUncomment,
  copyLineDown: () => copyLineDown,
  copyLineUp: () => copyLineUp,
  cursorCharBackward: () => cursorCharBackward,
  cursorCharBackwardLogical: () => cursorCharBackwardLogical,
  cursorCharForward: () => cursorCharForward,
  cursorCharForwardLogical: () => cursorCharForwardLogical,
  cursorCharLeft: () => cursorCharLeft,
  cursorCharRight: () => cursorCharRight,
  cursorDocEnd: () => cursorDocEnd,
  cursorDocStart: () => cursorDocStart,
  cursorGroupBackward: () => cursorGroupBackward,
  cursorGroupForward: () => cursorGroupForward,
  cursorGroupForwardWin: () => cursorGroupForwardWin,
  cursorGroupLeft: () => cursorGroupLeft,
  cursorGroupRight: () => cursorGroupRight,
  cursorLineBoundaryBackward: () => cursorLineBoundaryBackward,
  cursorLineBoundaryForward: () => cursorLineBoundaryForward,
  cursorLineBoundaryLeft: () => cursorLineBoundaryLeft,
  cursorLineBoundaryRight: () => cursorLineBoundaryRight,
  cursorLineDown: () => cursorLineDown,
  cursorLineEnd: () => cursorLineEnd,
  cursorLineStart: () => cursorLineStart,
  cursorLineUp: () => cursorLineUp,
  cursorMatchingBracket: () => cursorMatchingBracket,
  cursorPageDown: () => cursorPageDown,
  cursorPageUp: () => cursorPageUp,
  cursorSubwordBackward: () => cursorSubwordBackward,
  cursorSubwordForward: () => cursorSubwordForward,
  cursorSyntaxLeft: () => cursorSyntaxLeft,
  cursorSyntaxRight: () => cursorSyntaxRight,
  defaultKeymap: () => defaultKeymap,
  deleteCharBackward: () => deleteCharBackward,
  deleteCharBackwardStrict: () => deleteCharBackwardStrict,
  deleteCharForward: () => deleteCharForward,
  deleteGroupBackward: () => deleteGroupBackward,
  deleteGroupForward: () => deleteGroupForward,
  deleteLine: () => deleteLine,
  deleteLineBoundaryBackward: () => deleteLineBoundaryBackward,
  deleteLineBoundaryForward: () => deleteLineBoundaryForward,
  deleteToLineEnd: () => deleteToLineEnd,
  deleteToLineStart: () => deleteToLineStart,
  deleteTrailingWhitespace: () => deleteTrailingWhitespace,
  emacsStyleKeymap: () => emacsStyleKeymap,
  history: () => history,
  historyField: () => historyField,
  historyKeymap: () => historyKeymap,
  indentLess: () => indentLess,
  indentMore: () => indentMore,
  indentSelection: () => indentSelection,
  indentWithTab: () => indentWithTab,
  insertBlankLine: () => insertBlankLine,
  insertNewline: () => insertNewline,
  insertNewlineAndIndent: () => insertNewlineAndIndent,
  insertNewlineKeepIndent: () => insertNewlineKeepIndent,
  insertTab: () => insertTab,
  invertedEffects: () => invertedEffects,
  isolateHistory: () => isolateHistory,
  lineComment: () => lineComment,
  lineUncomment: () => lineUncomment,
  moveLineDown: () => moveLineDown,
  moveLineUp: () => moveLineUp,
  redo: () => redo,
  redoDepth: () => redoDepth,
  redoSelection: () => redoSelection,
  selectAll: () => selectAll,
  selectCharBackward: () => selectCharBackward,
  selectCharBackwardLogical: () => selectCharBackwardLogical,
  selectCharForward: () => selectCharForward,
  selectCharForwardLogical: () => selectCharForwardLogical,
  selectCharLeft: () => selectCharLeft,
  selectCharRight: () => selectCharRight,
  selectDocEnd: () => selectDocEnd,
  selectDocStart: () => selectDocStart,
  selectGroupBackward: () => selectGroupBackward,
  selectGroupForward: () => selectGroupForward,
  selectGroupForwardWin: () => selectGroupForwardWin,
  selectGroupLeft: () => selectGroupLeft,
  selectGroupRight: () => selectGroupRight,
  selectLine: () => selectLine,
  selectLineBoundaryBackward: () => selectLineBoundaryBackward,
  selectLineBoundaryForward: () => selectLineBoundaryForward,
  selectLineBoundaryLeft: () => selectLineBoundaryLeft,
  selectLineBoundaryRight: () => selectLineBoundaryRight,
  selectLineDown: () => selectLineDown,
  selectLineEnd: () => selectLineEnd,
  selectLineStart: () => selectLineStart,
  selectLineUp: () => selectLineUp,
  selectMatchingBracket: () => selectMatchingBracket,
  selectPageDown: () => selectPageDown,
  selectPageUp: () => selectPageUp,
  selectParentSyntax: () => selectParentSyntax,
  selectSubwordBackward: () => selectSubwordBackward,
  selectSubwordForward: () => selectSubwordForward,
  selectSyntaxLeft: () => selectSyntaxLeft,
  selectSyntaxRight: () => selectSyntaxRight,
  simplifySelection: () => simplifySelection,
  splitLine: () => splitLine,
  standardKeymap: () => standardKeymap,
  temporarilySetTabFocusMode: () => temporarilySetTabFocusMode,
  toggleBlockComment: () => toggleBlockComment,
  toggleBlockCommentByLine: () => toggleBlockCommentByLine,
  toggleComment: () => toggleComment,
  toggleLineComment: () => toggleLineComment,
  toggleTabFocusMode: () => toggleTabFocusMode,
  transposeChars: () => transposeChars,
  undo: () => undo,
  undoDepth: () => undoDepth,
  undoSelection: () => undoSelection,
};
var codemirrorSearch = {
  RegExpCursor: () => RegExpCursor,
  SearchCursor: () => SearchCursor,
  SearchQuery: () => SearchQuery,
  closeSearchPanel: () => closeSearchPanel,
  findNext: () => findNext,
  findPrevious: () => findPrevious,
  getSearchQuery: () => getSearchQuery,
  gotoLine: () => gotoLine,
  highlightSelectionMatches: () => highlightSelectionMatches,
  openSearchPanel: () => openSearchPanel,
  replaceAll: () => replaceAll,
  replaceNext: () => replaceNext,
  search: () => search,
  searchKeymap: () => searchKeymap,
  searchPanelOpen: () => searchPanelOpen,
  selectMatches: () => selectMatches,
  selectNextOccurrence: () => selectNextOccurrence,
  selectSelectionMatches: () => selectSelectionMatches,
  setSearchQuery: () => setSearchQuery,
};
var lezerLr = {
  ContextTracker: () => ContextTracker,
  ExternalTokenizer: () => ExternalTokenizer,
  InputStream: () => InputStream,
  LRParser: () => LRParser,
  LocalTokenGroup: () => LocalTokenGroup,
  Stack: () => Stack,
};
var codemirrorClosebrackets = {
  CompletionContext: () => CompletionContext,
  acceptCompletion: () => acceptCompletion,
  autocompletion: () => autocompletion,
  clearSnippet: () => clearSnippet,
  closeBrackets: () => closeBrackets,
  closeBracketsKeymap: () => closeBracketsKeymap,
  closeCompletion: () => closeCompletion,
  completeAnyWord: () => completeAnyWord,
  completeFromList: () => completeFromList,
  completionKeymap: () => completionKeymap,
  completionStatus: () => completionStatus,
  currentCompletions: () => currentCompletions,
  deleteBracketPair: () => deleteBracketPair,
  hasNextSnippetField: () => hasNextSnippetField,
  hasPrevSnippetField: () => hasPrevSnippetField,
  ifIn: () => ifIn,
  ifNotIn: () => ifNotIn,
  insertBracket: () => insertBracket,
  insertCompletionText: () => insertCompletionText,
  moveCompletionSelection: () => moveCompletionSelection,
  nextSnippetField: () => nextSnippetField,
  pickedCompletion: () => pickedCompletion,
  prevSnippetField: () => prevSnippetField,
  selectedCompletion: () => selectedCompletion,
  selectedCompletionIndex: () => selectedCompletionIndex,
  setSelectedCompletion: () => setSelectedCompletion,
  snippet: () => snippet,
  snippetCompletion: () => snippetCompletion,
  snippetKeymap: () => snippetKeymap,
  startCompletion: () => startCompletion,
};
var u = {
  Component: () => Component,
  Events: () => Events,
  MarkdownPreviewRenderer: () => MarkdownPreviewRenderer,
  MarkdownRenderChild: () => MarkdownRenderChild,
  Notice: () => Notice,
  Publish: () => Publish,
  addIcon: () => addIcon,
  getIcon: () => getIcon,
  getIconIds: () => getIconIds,
  moment: () => moment,
  parseYaml: () => parseYaml,
  removeIcon: () => removeIcon,
  setIcon: () => setIcon,
  stringifyYaml: () => stringifyYaml,
};
var codemirrorCollab = {
  collab: () => collab,
  getClientID: () => getClientID,
  getSyncedVersion: () => getSyncedVersion,
  rebaseUpdates: () => rebaseUpdates,
  receiveUpdates: () => receiveUpdates,
  sendableUpdates: () => sendableUpdates,
};
const {
  closeLintPanel,
  diagnosticCount,
  forEachDiagnostic,
  forceLinting,
  lintGutter,
  lintKeymap,
  linter,
  nextDiagnostic,
  openLintPanel,
  previousDiagnostic,
  setDiagnostics,
  setDiagnosticsEffect,
} = require("@codemirror/lint");
var codemirrorLint = {
  closeLintPanel: () => closeLintPanel,
  diagnosticCount: () => diagnosticCount,
  forEachDiagnostic: () => forEachDiagnostic,
  forceLinting: () => forceLinting,
  lintGutter: () => lintGutter,
  lintKeymap: () => lintKeymap,
  linter: () => linter,
  nextDiagnostic: () => nextDiagnostic,
  openLintPanel: () => openLintPanel,
  previousDiagnostic: () => previousDiagnostic,
  setDiagnostics: () => setDiagnostics,
  setDiagnosticsEffect: () => setDiagnosticsEffect,
};
var obsidian = {
  AbstractInputSuggest: () => AbstractInputSuggest,
  AbstractTextComponent: () => AbstractTextComponent,
  App: () => App,
  BaseComponent: () => BaseComponent,
  BasesView: () => BasesView,
  ButtonComponent: () => ButtonComponent,
  CapacitorAdapter: () => CapacitorAdapter,
  ColorComponent: () => ColorComponent,
  Component: () => Component,
  DropdownComponent: () => DropdownComponent,
  EditableFileView: () => EditableFileView,
  Editor: () => Editor,
  EditorSuggest: () => EditorSuggest,
  Events: () => Events,
  ExtraButtonComponent: () => ExtraButtonComponent,
  FileManager: () => FileManager,
  FileSystemAdapter: () => FileSystemAdapter,
  FileView: () => FileView,
  FuzzySuggestModal: () => FuzzySuggestModal,
  HoverPopover: () => HoverPopover,
  ItemView: () => ItemView,
  Keymap: () => Keymap,
  MarkdownPreviewRenderer: () => MarkdownPreviewRenderer,
  MarkdownPreviewSection: () => MarkdownPreviewSection,
  MarkdownPreviewView: () => MarkdownPreviewView,
  MarkdownRenderChild: () => MarkdownRenderChild,
  MarkdownRenderer: () => MarkdownRenderer,
  MarkdownView: () => MarkdownView,
  Menu: () => Menu,
  MenuItem: () => MenuItem,
  MenuSeparator: () => MenuSeparator,
  MetadataCache: () => MetadataCache,
  Modal: () => Modal,
  MomentFormatComponent: () => MomentFormatComponent,
  Notice: () => Notice,
  Platform: () => Platform,
  Plugin: () => Plugin,
  PluginSettingTab: () => PluginSettingTab,
  PopoverState: () => PopoverState,
  PopoverSuggest: () => PopoverSuggest,
  ProgressBarComponent: () => ProgressBarComponent,
  Scope: () => Scope,
  SearchComponent: () => SearchComponent,
  Setting: () => Setting,
  SettingTab: () => SettingTab,
  SliderComponent: () => SliderComponent,
  SuggestModal: () => SuggestModal,
  TAbstractFile: () => TAbstractFile,
  TFile: () => TFile,
  TFolder: () => TFolder,
  TextAreaComponent: () => TextAreaComponent,
  TextComponent: () => TextComponent,
  TextFileView: () => TextFileView,
  ToggleComponent: () => ToggleComponent,
  ValueComponent: () => ValueComponent,
  Vault: () => Vault,
  View: () => View,
  ViewRegistry: () => ViewRegistry,
  Workspace: () => Workspace,
  WorkspaceContainer: () => WorkspaceContainer,
  WorkspaceFloating: () => WorkspaceFloating,
  WorkspaceItem: () => WorkspaceItem,
  WorkspaceLeaf: () => WorkspaceLeaf,
  WorkspaceParent: () => WorkspaceParent,
  WorkspaceRibbon: () => WorkspaceRibbon,
  WorkspaceRoot: () => WorkspaceRoot,
  WorkspaceSidedock: () => WorkspaceSidedock,
  WorkspaceSplit: () => WorkspaceSplit,
  WorkspaceTabs: () => WorkspaceTabs,
  WorkspaceWindow: () => WorkspaceWindow,
  addIcon: () => addIcon,
  apiVersion: () => apiVersion,
  arrayBufferToBase64: () => arrayBufferToBase64,
  arrayBufferToHex: () => arrayBufferToHex,
  base64ToArrayBuffer: () => base64ToArrayBuffer,
  debounce: () => debounce,
  displayTooltip: () => displayTooltip,
  editorEditorField: () => editorEditorField,
  editorInfoField: () => editorInfoField,
  editorLivePreviewField: () => editorLivePreviewField,
  editorViewField: () => editorViewField,
  finishRenderMath: () => finishRenderMath,
  fuzzySearch: () => fuzzySearch,
  getAllTags: () => getAllTags,
  getBlobArrayBuffer: () => getBlobArrayBuffer,
  getFrontMatterInfo: () => getFrontMatterInfo,
  getIcon: () => getIcon,
  getIconIds: () => getIconIds,
  getLanguage: () => getLanguage,
  getLinkpath: () => getLinkpath,
  hexToArrayBuffer: () => hexToArrayBuffer,
  htmlToMarkdown: () => htmlToMarkdown,
  iterateCacheRefs: () => iterateCacheRefs,
  iterateRefs: () => iterateRefs,
  livePreviewState: () => livePreviewState,
  loadMathJax: () => loadMathJax,
  loadMermaid: () => loadMermaid,
  loadPdfJs: () => loadPdfJs,
  loadPrism: () => loadPrism,
  moment: () => moment,
  normalizePath: () => normalizePath,
  parseFrontMatterAliases: () => parseFrontMatterAliases,
  parseFrontMatterEntry: () => parseFrontMatterEntry,
  parseFrontMatterStringArray: () => parseFrontMatterStringArray,
  parseFrontMatterTags: () => parseFrontMatterTags,
  parseLinktext: () => parseLinktext,
  parseYaml: () => parseYaml,
  prepareFuzzySearch: () => prepareFuzzySearch,
  prepareQuery: () => prepareQuery,
  prepareSimpleSearch: () => prepareSimpleSearch,
  removeIcon: () => removeIcon,
  renderMatches: () => renderMatches,
  renderMath: () => renderMath,
  renderResults: () => renderResults,
  request: () => request,
  requestUrl: () => requestUrl,
  requireApiVersion: () => requireApiVersion,
  resolveSubpath: () => resolveSubpath,
  sanitizeHTMLToDom: () => sanitizeHTMLToDom,
  setIcon: () => setIcon,
  setTooltip: () => setTooltip,
  sortSearchResults: () => sortSearchResults,
  stringifyYaml: () => stringifyYaml,
  stripHeading: () => stripHeading,
  stripHeadingForLink: () => stripHeadingForLink,
};
/** tslib */