"use strict";

const fs = require("fs");
const path = require("path");
const readline = require("readline");

/**
 * 流式处理器：将大文件分割成多个模块
 */
async function splitFile(inputPath, outputDir) {
  const fileStream = fs.createReadStream(inputPath);
  const rl = readline.createInterface({
    input: fileStream,
    crlfDelay: Infinity
  });

  // 读取分析结果
  const analysisPath = '/tmp/analysis.json';
  if (!fs.existsSync(analysisPath)) {
    throw new Error('Analysis file not found. Run refactor.js first.');
  }
  const declarations = JSON.parse(fs.readFileSync(analysisPath, 'utf8'));

  // 计算每个声明的结束行（下一个声明的开始行 -1）
  for (let i = 0; i < declarations.length - 1; i++) {
    declarations[i].endLine = declarations[i + 1].line - 1;
  }
  // 最后一个声明的结束行需要估算
  declarations[declarations.length - 1].endLine = null; // 稍后确定

  // 创建模块分组逻辑
  const modules = [];
  let currentModule = {
    name: 'module_0',
    startLine: 1,
    declarations: [],
    estimatedLines: 0
  };
  
  const MAX_LINES_PER_MODULE = 4500; // 留有余地，确保不超过 5000 行
  
  let currentLine = 1;
  let moduleIndex = 0;
  let linesInCurrentModule = 0;
  
  for (const decl of declarations) {
    const declSize = decl.endLine ? decl.endLine - decl.line + 1 : 5000; // 最后一个估计
    
    if (linesInCurrentModule + declSize > MAX_LINES_PER_MODULE && currentModule.declarations.length > 0) {
      // 完成当前模块
      currentModule.endLine = decl.line - 1;
      modules.push(currentModule);
      
      // 开始新模块
      moduleIndex++;
      currentModule = {
        name: `module_${moduleIndex}`,
        startLine: decl.line,
        declarations: [],
        estimatedLines: 0
      };
      linesInCurrentModule = 0;
    }
    
    currentModule.declarations.push(decl);
    linesInCurrentModule += declSize;
  }
  
  // 添加最后一个模块
  if (currentModule.declarations.length > 0) {
    currentModule.endLine = 130191; // 文件总行数
    modules.push(currentModule);
  }

  console.error(`Created ${modules.length} modules`);
  
  // 现在使用流式方式提取每个模块的代码
  for (const module of modules) {
    await extractModule(inputPath, outputDir, module);
  }
  
  return modules;
}

/**
 * 流式提取模块代码
 */
async function extractModule(inputPath, outputDir, moduleInfo) {
  const fileStream = fs.createReadStream(inputPath);
  const rl = readline.createInterface({
    input: fileStream,
    crlfDelay: Infinity
  });

  const lines = [];
  let lineNumber = 0;
  const { startLine, endLine, name, declarations } = moduleInfo;
  
  console.error(`Extracting ${name}: lines ${startLine}-${endLine || 'end'} (${declarations.length} declarations)`);

  for await (const line of rl) {
    lineNumber++;
    
    if (lineNumber >= startLine && (endLine === null || lineNumber <= endLine)) {
      lines.push(line);
    }
    
    if (endLine && lineNumber > endLine) {
      break;
    }
    
    // 进度报告
    if (lineNumber % 20000 === 0) {
      console.error(`  Reading line ${lineNumber}...`);
    }
  }

  // 生成模块文件
  const moduleContent = generateModuleContent(name, declarations, lines);
  const outputPath = path.join(outputDir, `${name}.js`);
  fs.writeFileSync(outputPath, moduleContent);
  
  console.error(`  Written to ${outputPath} (${lines.length} lines)`);
}

/**
 * 生成模块内容，包含明确的 exports
 */
function generateModuleContent(moduleName, declarations, lines) {
  const header = `"use strict";\n\n// Module: ${moduleName}\n// Auto-generated by refactor script\n\n`;
  
  // 收集需要导出的标识符
  const exports_list = declarations
    .filter(d => d.type !== 'exports')
    .map(d => d.name);
  
  // 生成导出语句
  const exportStatement = `\n// Explicit exports\nmodule.exports = {\n${exports_list.map(name => `  ${name},`).join('\n')}\n};\n`;
  
  return header + lines.join('\n') + exportStatement;
}

// 主函数
async function main() {
  const inputFile = process.argv[2] || '/workspace/src/obsidian/app.js';
  const outputDir = process.argv[3] || '/workspace/src/obsidian/modules/output';
  
  // 创建输出目录
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }
  
  console.error(`Splitting ${inputFile} into modules in ${outputDir}...`);
  const modules = await splitFile(inputFile, outputDir);
  
  console.error(`\nCreated ${modules.length} module files:`);
  modules.forEach(m => {
    console.error(`  - ${m.name}.js: lines ${m.startLine}-${m.endLine} (${m.declarations.length} declarations)`);
  });
}

main().catch(console.error);
